### ISSUE TITLE
calculator

### ISSUE THREAD

**Issue by kateluxemburg** [colindean/wilkinsburg_pittsburgh_merger_analysis#1]
Hello Colin,  

As I said at the meeting at Eastridge branch of Wilkinsburg library, the calculator is engaging.  I would like to make a link directly to the calculator from WilkinsburgFuture.org.  Would you change the calculator to use the new school district real estate tax, adopted this past Tuesday-- 26.5 mills, replacing 29.5 mills.

The support for annexation is mostly by people who overpaid for their houses-- came from other cities where prices are higher than here or fell in love with a house they could not have afforded if it was priced in Pittsburgh and did not have the price adjustment some sellers agree to expecting their buyers to know about the real estate tax and the school district assessment appeals of new sales.  Look at 901 Savannah - Owner History.  This property is now two years tax delinquent after the assessment was increased to sale price adjusted by common level ratio.  I think the range of the assessments you show in the heat map does not include property assessments this high-- but I can't see it while I am typing.  I could send you a list of all Wilkinsburg property assessments.

Kate Luxemburg
kateluxemburg@gmail.com

**Comment by colindean** [comment]
Thanks for opening a ticket!

> I would like to make a link directly to the calculator from WilkinsburgFuture.org.

Please do!

> Would you change the calculator to use the new school district real estate tax, adopted this past Tuesday-- 26.5 mills, replacing 29.5 mills?

I'll happily update the millage! Can you provide something reflecting that change? I'd like to cite a news article or press release or publicly available minutes since that rate probably won't be on widely available tables for a while. The latest board minutes available are [May 2021](https://www.wilkinsburgschools.org/wp-content/uploads/2021/06/Board-Minutes-May-2021.pdf) and there's not a mention or action therein.

> sale price adjusted by common level ratio

A lawsuit was filed last week against the county alleging that it codes sales in a way that [unfairly increases the county's CLR](https://www.post-gazette.com/business/development/2021/06/29/Allegheny-County-property-assessments-sales-Common-Pleas-Court-lawsuit-John-Silvestri/stories/202106290071). Reassessment came up at the meeting last night but I'm unsure how to factor that into materials I'm presenting other than as a footnote saying "your assessment could go up" but that's _generally_ true and likely to occur in 2022 for the 2023 tax year if the county's reassessment continues its approximately decennial cadence (2001 for 2002 tax year, 2012 for 2013 tax year...).

I got hit bad by reassessment in 2013. IIRC, when I bought my house, its assessment was around $55k and it was reassessed to $101k _after_ I fought it down from a $110k assessment when I'd bought it for $100k a year earlier!

> I think the range of the assessments you show in the heat map does not include property assessments this high-- but I can't see it while I am typing. 

For passers-by, the assessed value of the referenced property is around $380k, which is the sixth-highest assessment in the borough. Found with:

```bash
xsv sort --numeric --select COUNTYTOTAL wilkinsburg-residence.csv | xsv select COUNTYTOTAL,PROPERTYHOUSENUM,PROPERTYADDRESS
``` 

The graph doesn't go that high. I went only to two standard deviations above the mean, $190k, in order for the graph to be more indicative for those with lower property values and then implemented the calculator for precision. There are 131 properties above $190k of 6425 properties marked as residences (`wc -l wilkinsburg-residence.csv`), about 2%.

> I could send you a list of all Wilkinsburg property assessments.

I'm retrieving the data from the WPRDC, which says the data is up to date as of June 2021:

https://github.com/colindean/wilkinsburg_pittsburgh_merger_analysis/blob/ffe0d7691e2153f7b5a1215a09ee676535e3f318/Makefile#L1-L2

Is there a better source for the data?

**Comment by kateluxemburg** [comment]
Hi, Here is a short reply from my phone keyboard. This for me is a really
interesting discussion, property data. WPRDC is the source I use as well.

Most people do not download the assessments dataset which is updated
monthly because it is a large file, has a record for every property in the
county. That is why I offered  to send you all Wilkinsburg, which is only
available from that dataset. Now I realize you do have it. Most people
download the sales dataset, only has deed transfers.

I will get a document from the school district verifying the new millage. I
suspect there will not be a press release because the school board
president is openly disrespectful of borough council and does not want to
put a brake on annexation push.

Most of the support for annexation comes from those 2 percent of
residential properties with highest assessments. Of course. I think it is
good to show that.

It is the policy of the school district to file assessment appeals on all
previous year sales where the difference between current assessment and
sale price adjusted downward by CLR exceeds $5000. There is no deviation
from that in practice. I check. And for the past two years, BPAAR was
consistent in deciding appeals to sale price adjusted by CLR. I have the
data. So when a house sells for a price way over assessment, we know what
to expect.

I do not expect another countywide reassessment 10 years after the work if
the last was done, 2012.  Rich F and other elected officials say
straightforwardly they want to avoid doing it.

More later.

**Comment by colindean** [comment]
Thank you for the excellent information!

I'm finding that there are several hundred residential properties with _very_ low assessments, e.g. below $1,000. What is your insight on these? 

Should I be pruning $0 assessments from the data for basic stats purposes? There are 147 of those alone.

![wilkinsburg_residence_assessments](https://user-images.githubusercontent.com/197224/124366046-c5292300-dc1a-11eb-9a70-cee813df921d.png)

**Comment by kateluxemburg** [comment]
Here is more reply, now from my desktop computer where I can easily
scroll to see your message while I am replying.

The 2102 countywide reassessment raised the value of your property from
87900 to 108000.  I have assessments as far back as 2006, and your property
was 87900 in that year.  It looks like you were able to get the CAMA
assessment reduced by arguing the 2011 sale price.
[image: image.png]
[image: image.png]
Thank you for bringing to my attention the case filed against Allegheny
County CLR,  I had not seen it.  Case ID is GD-21-007154.  The lead
plaintiff Madelyn Gioffre is a participant in the WCDC so-called "merger
analysis."  (I prefer the term "annexation" and I think WCDC is not up to
doing good analysis.)  I am reading the amended complaint for the case and
wondering how they can get to where they want to go with it.

Just now I saw your new message, asking about low value properties.  Note
whether the fairMarketBuilding = 0 -- meaning the value is land only, a
vacant lot.  Also look at the useDesc (use description).  I am going out to
look at a tax sale property right now.

**Comment by colindean** [comment]
Awesome. Thanks for the reminder of the correct figures. I guess I was waaaay off about the assessment of my house when I bought it. It's been 10 years 😉 

Your image attachments didn't come through. You'll need to upload them directly on GitHub itself. You can edit your comment if you'd like to but obvs please ensure that addresses are censored.

I'll drum up something to exclude where `fairmarketbuilding == 0` and adjust the lines on the graphs.

**Comment by colindean** [comment]
Oh snap:

```bash
xsv frequency --select USEDESC wilkinsburg-residence.csv 
```
```csv
field,value,count
USEDESC,SINGLE FAMILY,3811
USEDESC,VACANT LAND,968
USEDESC,TWO FAMILY,618
USEDESC,CONDOMINIUM,372
USEDESC,THREE FAMILY,245
USEDESC,ROWHOUSE,180
USEDESC,FOUR FAMILY,74
USEDESC,RES AUX BUILDING (NO HOUSE),53
USEDESC,CONDEMNED/BOARDED-UP,51
USEDESC,TOWNHOUSE,43
```

Looks like there are several `USEDESC` to exclude, too.

Passers-by: N.b. this only affects the mean, median, and other statistic markers on the tax graphs.

**Comment by colindean** [comment]
WSD RET millage updated on the calculator to 26.5 mills but I need to regenerate the graphs. I'll do that early this afternoon.

**Comment by colindean** [comment]
I regenerated those graphs a while ago and just regenerated them again having found a bug in the math (#6) while solving #5. Things look more correct now!
